Correct encoding unsigned integers
gosnmp/gosnmp pull request #377
Opened 2021-10-30 12:26 UTC by it1804

All integers within SNMP are encoded as signed. Meaning a value above 2^31-1 must be encoded in 5 bytes. 

Signed-off-by: Ivan Torgashov <it1804@mail.ru>

2021-10-30 13:01 UTC, it1804 commented
For example, the ciscoResponseBytes in marshal_test.go is encoded by Gauge32 with the value 4294967295 in 5 bytes, not 4.
Unfortunately, I could not find this condition in the coding rules, but my test requests confirm this.
Traffic dumps confirm for:
0x7FFFFFFF:
```snmpset -v 1 -c private 192.168.100.124 .1.3.6.1.4.1.318.1.1.4.4.2.1.3.5 u 2147483647```
0x0080000000:
```snmpset -v 1 -c private 192.168.100.124 .1.3.6.1.4.1.318.1.1.4.4.2.1.3.5 u 2147483648```

Although snmpset generates the same five-byte values for INTEGER (i) in the case> 2147483647, I think this is incorrect. Documentary evidence is required.

2021-11-01 21:24 UTC, TimRots reviewed
Nice. Left some minor comments to improve error handling.

2022-02-22 20:57 UTC, TimRots commented
Hi @it1804. Sorry for only getting back to this now. Would it be possible to resolve the merge conflict on this branch? Thinking this PR would be a good enhancement to add. Thanks in advance.

2022-02-27 19:53 UTC, it1804 commented
Hi! The conflict has been resolved.

2022-02-28 00:54 UTC, TimRots requested changes
Thank you @it1804. Left some minor nits and then this should be ready :)

2022-02-28 00:54 UTC, TimRots commented on helper_test.go
> +	{18542501, []byte{0x01, 0x1a, 0xef, 0xa5}},
I think we should remove this duplicate entry for ``18542501``

2022-02-28 00:54 UTC, TimRots commented on helper.go
> +	for ; i < 3; i++ {
It's probably more idiomatic to write this for loop as:
```go
for i := 0; i < 3; i++ {
```

2022-02-28 19:30 UTC, TimRots commented
@SuperQ Can you give this PR a final review please? Thanks in advance.

2022-03-02 07:02 UTC, SuperQ approved these changes
LGTM

2022-03-02 07:45 UTC, merged