Add Hex-String solutions to examples
gosnmp/gosnmp pull request #390
Opened 2022-01-07 08:08 UTC by Laurel-rao

Signed-off-by: raojiajun <13694846652@163.com>

2022-03-05 15:29 UTC, TimRots requested changes
Left some comments. 
You could run ``gofmt`` on the code to catch most of these issues.

2022-03-05 15:29 UTC, TimRots commented on examples/Hex-String/main.go
> +package main
Please add copyright/license header as with other examples
```
// Copyright 2012 The GoSNMP Authors. All rights reserved.  Use of this
// source code is governed by a BSD-style license that can be found in the
// LICENSE file.
```

2022-03-05 15:29 UTC, TimRots commented on examples/Hex-String/main.go
> +				for i := 0;i < len(value);i ++ {
```go
				for i := 0; i < len(value); i++ {
```

2022-03-05 15:29 UTC, TimRots commented on examples/Hex-String/main.go
> +			}	else {
```go
} else {
```

2022-03-21 06:53 UTC, Laurel-rao commented
i already adjust the style problem that we talk about it, please check code then merge the pull request

2023-05-22 18:58 UTC, TimRots approved these changes

2023-05-22 19:00 UTC, merged